# general settings
# name: debug_DBCNN_LIVEC
name: dbcnn_spaq
model_type: DBCNNModel
num_gpu: 1  # set num_gpu: 0 for cpu mode
manual_seed: 123

# dataset and data loader settings
datasets:
  train:
    name: spaq
    type: GeneralJSONDataset
    dataroot_target: ./data
    meta_info_file: ./data_json/for_cross_set/train/spaq_train.json
    mos_range: [0, 100]
    lower_better: false 
    mos_normalize: false

    augment:
      hflip: true
      random_crop: 384
    img_range: 1

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 4
    batch_size_per_gpu: 8
    dataset_enlarge_ratio: 1
    prefetch_mode: ~

  val_0:
    name: koniq10k
    type: GeneralJSONDataset
    dataroot_target: ./data
    meta_info_file: ./data_json/for_cross_set/test/koniq10k_test.json
  val_1:
    name: spaq
    type: GeneralJSONDataset
    dataroot_target: ./data
    meta_info_file: ./data_json/for_cross_set/test/spaq_test.json
    augment:
      resize: 768
  val_2:
    name: livec
    type: GeneralJSONDataset
    dataroot_target: ./data
    meta_info_file: ./data_json/for_cross_set/test/livec.json
  val_3:
    name: agiqa3k
    type: GeneralJSONDataset
    dataroot_target: ./data
    meta_info_file: ./data_json/for_cross_set/test/agiqa3k.json
  val_4:
    name: kadid10k
    type: GeneralJSONDataset
    dataroot_target: ./data
    meta_info_file: ./data_json/for_cross_set/test/kadid10k_test.json
  val_5:
    name: live
    type: GeneralJSONDataset
    dataroot_target: ./data
    meta_info_file: ./data_json/for_cross_set/test/live.json
    lower_better: true 
  val_6:
    name: csiq
    type: GeneralJSONDataset
    dataroot_target: ./data
    meta_info_file: ./data_json/for_cross_set/test/csiq.json
    lower_better: true 
  val_7:
    name: bid
    type: GeneralJSONDataset
    dataroot_target: ./data
    meta_info_file: ./data_json/for_cross_set/test/bid.json
    augment:
      resize: 768
  val_8:
    name: cid2013
    type: GeneralJSONDataset
    dataroot_target: ./data
    meta_info_file: ./data_json/for_cross_set/test/cid2013.json
    augment:
      resize: 768

# network structures
network:
  type: DBCNN
  pretrained: false

# path
path:
  pretrain_network_g: ~
  strict_load_g: true
  resume_state: ~

# training settings
train:
  optim:
    type: SGD
    lr: !!float 1e-3
    momentum: 0.9
    weight_decay: !!float 5e-4

  optim_finetune:
    type: Adam
    lr: !!float 1e-5
    weight_decay: !!float 5e-4

  scheduler:
    type: MultiStepLR
    milestones: [1000]
    gamma: 1

  scheduler_finetune:
    type: MultiStepLR
    milestones: [1000]
    gamma: 1

  total_iter: 20000 # 883 iter/epoch, train/finetune for about 30 epochs
  finetune_start_iter: 10000
  warmup_iter: -1  # no warm up

  # losses
  mos_loss_opt:
    type: MSELoss
    loss_weight: !!float 1.0
  
# validation settings
val:
  val_freq: !!float 800
  save_img: false
  pbar: true

  key_metric: srcc # if this metric improve, update all metrics. If not specified, each best metric results will be updated separately
  metrics:
    srcc:
      type: calculate_srcc

    plcc:
      type: calculate_plcc

    krcc:
      type: calculate_krcc

# logging settings
logger:
  print_freq: 100
  save_latest_freq: !!float 5e2
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500
